package com.ljheee.reverse;
// Generated 2016-9-2 11:26:57 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Persons generated by hbm2java
 */
public class Persons implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer age;
	private Set<Phones> phoneses = new HashSet<Phones>(0);

	public Persons() {
	}

	public Persons(String name) {
		this.name = name;
	}

	public Persons(String name, Integer age, Set<Phones> phoneses) {
		this.name = name;
		this.age = age;
		this.phoneses = phoneses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public Set<Phones> getPhoneses() {
		return this.phoneses;
	}

	public void setPhoneses(Set<Phones> phoneses) {
		this.phoneses = phoneses;
	}

}
