package com.ljheee.reverse;
// Generated 2016-9-2 11:26:57 by Hibernate Tools 4.3.1.Final

/**
 * Phones generated by hbm2java
 */
public class Phones implements java.io.Serializable {

	private Integer id;
	private Persons persons;
	private String phone;

	public Phones() {
	}

	public Phones(Persons persons, String phone) {
		this.persons = persons;
		this.phone = phone;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Persons getPersons() {
		return this.persons;
	}

	public void setPersons(Persons persons) {
		this.persons = persons;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

}
